# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.tolba.com:
  peer0.cib.tolba.com:
  peer1.cib.tolba.com:
  peer0.hsbc.tolba.com:
  peer1.hsbc.tolba.com:
  peer0.qnb.tolba.com:
  peer1.qnb.tolba.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cib
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cib.tolba.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f940cab49ffd8a01003cdc7a1d1f7255d51efb69c2b51886e509d1ea15c31364_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cib.tolba.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f940cab49ffd8a01003cdc7a1d1f7255d51efb69c2b51886e509d1ea15c31364_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/cib.tolba.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCIB
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hsbc
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hsbc.tolba.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2f5b5cc589ca160c212ab044cff3cc617c720773c30ac8f3f8f26edf62de5dd2_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hsbc.tolba.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2f5b5cc589ca160c212ab044cff3cc617c720773c30ac8f3f8f26edf62de5dd2_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hsbc.tolba.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHSBC
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-qnb
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.qnb.tolba.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.qnb.tolba.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/q.tolba.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerQNB
    networks:
      - byfn

  orderer.tolba.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.tolba.com
    container_name: orderer.tolba.com
    networks:
      - byfn

  peer0.cib.tolba.com:
    container_name: peer0.cib.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cib.tolba.com
    networks:
      - byfn

  peer1.cib.tolba.com:
    container_name: peer1.cib.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cib.tolba.com
    networks:
      - byfn

  peer0.hsbc.tolba.com:
    container_name: peer0.hsbc.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hsbc.tolba.com
    networks:
      - byfn

  peer1.hsbc.tolba.com:
    container_name: peer1.hsbc.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hsbc.tolba.com
    networks:
      - byfn

 peer0.qnb.tolba.com:
    container_name: peer0.qnb.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.qnb.tolba.com
    networks:
      - byfn

  peer1.qnb.tolba.com:
    container_name: peer1.qnb.tolba.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.qnb.tolba.com
    networks:
      - byfn
